from __future__ import annotations


CANONICAL_ENTITIES: dict[str, str] = {
    "Apple": "ORG",
    "Samsung": "ORG",
    "Huawei": "ORG",
    "OpenAI": "ORG",
    "Anthropic": "ORG",
    "NVIDIA": "ORG",
    "Qualcomm": "ORG",
    "Tencent": "ORG",
    "Alibaba": "ORG",
    "ByteDance": "ORG",
    "Xiaomi": "ORG",
    "Google": "ORG",
    "Microsoft": "ORG",
    "Meta": "ORG",
    "Amazon": "ORG",
    "Tesla": "ORG",
    "SpaceX": "ORG",
    "ChatGPT": "PRODUCT",
    "GPT-4": "PRODUCT",
    "GPT-5": "PRODUCT",
    "Claude": "PRODUCT",
    "Gemini": "PRODUCT",
    "Llama": "PRODUCT",
    "Stable Diffusion": "PRODUCT",
    "Midjourney": "PRODUCT",
    "iOS": "PRODUCT",
    "Android": "PRODUCT",
    "HarmonyOS": "PRODUCT",
    "macOS": "PRODUCT",
    "Windows": "PRODUCT",
    "Tim Cook": "PERSON",
    "Jensen Huang": "PERSON",
    "Sam Altman": "PERSON",
    "Elon Musk": "PERSON",
}
