from __future__ import annotations


ALIAS_MAP: dict[str, str] = {
    "apple": "Apple",
    "apple inc": "Apple",
    "apple inc.": "Apple",
    "苹果": "Apple",
    "苹果公司": "Apple",
    "huawei": "Huawei",
    "华为": "Huawei",
    "华为公司": "Huawei",
    "openai": "OpenAI",
    "open ai": "OpenAI",
    "anthropic": "Anthropic",
    "nvidia": "NVIDIA",
    "英伟达": "NVIDIA",
    "qualcomm": "Qualcomm",
    "高通": "Qualcomm",
    "tencent": "Tencent",
    "腾讯": "Tencent",
    "alibaba": "Alibaba",
    "阿里巴巴": "Alibaba",
    "bytedance": "ByteDance",
    "字节跳动": "ByteDance",
    "xiaomi": "Xiaomi",
    "小米": "Xiaomi",
    "google": "Google",
    "谷歌": "Google",
    "microsoft": "Microsoft",
    "微软": "Microsoft",
    "meta": "Meta",
    "amazon": "Amazon",
    "tesla": "Tesla",
    "特斯拉": "Tesla",
    "spacex": "SpaceX",
    "chatgpt": "ChatGPT",
    "gpt4": "GPT-4",
    "gpt-4": "GPT-4",
    "gpt5": "GPT-5",
    "gpt-5": "GPT-5",
    "claude": "Claude",
    "gemini": "Gemini",
    "llama": "Llama",
    "stable diffusion": "Stable Diffusion",
    "midjourney": "Midjourney",
    "ios": "iOS",
    "iphone os": "iOS",
    "android": "Android",
    "安卓": "Android",
    "harmonyos": "HarmonyOS",
    "鸿蒙": "HarmonyOS",
    "macos": "macOS",
    "windows": "Windows",
    "tim cook": "Tim Cook",
    "库克": "Tim Cook",
    "jensen huang": "Jensen Huang",
    "黄仁勋": "Jensen Huang",
    "sam altman": "Sam Altman",
    "奥特曼": "Sam Altman",
    "elon musk": "Elon Musk",
    "马斯克": "Elon Musk",
}
